// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster/internal/data.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WriteShardRequest struct {
	ShardID              uint64   `protobuf:"varint,1,opt,name=ShardID,proto3" json:"ShardID,omitempty"`
	Points               [][]byte `protobuf:"bytes,2,rep,name=Points,proto3" json:"Points,omitempty"`
	Database             string   `protobuf:"bytes,3,opt,name=Database,proto3" json:"Database,omitempty"`
	RetentionPolicy      string   `protobuf:"bytes,4,opt,name=RetentionPolicy,proto3" json:"RetentionPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteShardRequest) Reset()         { *m = WriteShardRequest{} }
func (m *WriteShardRequest) String() string { return proto.CompactTextString(m) }
func (*WriteShardRequest) ProtoMessage()    {}
func (*WriteShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{0}
}

func (m *WriteShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteShardRequest.Unmarshal(m, b)
}
func (m *WriteShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteShardRequest.Marshal(b, m, deterministic)
}
func (m *WriteShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteShardRequest.Merge(m, src)
}
func (m *WriteShardRequest) XXX_Size() int {
	return xxx_messageInfo_WriteShardRequest.Size(m)
}
func (m *WriteShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteShardRequest proto.InternalMessageInfo

func (m *WriteShardRequest) GetShardID() uint64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *WriteShardRequest) GetPoints() [][]byte {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *WriteShardRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *WriteShardRequest) GetRetentionPolicy() string {
	if m != nil {
		return m.RetentionPolicy
	}
	return ""
}

type WriteShardResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteShardResponse) Reset()         { *m = WriteShardResponse{} }
func (m *WriteShardResponse) String() string { return proto.CompactTextString(m) }
func (*WriteShardResponse) ProtoMessage()    {}
func (*WriteShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{1}
}

func (m *WriteShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteShardResponse.Unmarshal(m, b)
}
func (m *WriteShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteShardResponse.Marshal(b, m, deterministic)
}
func (m *WriteShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteShardResponse.Merge(m, src)
}
func (m *WriteShardResponse) XXX_Size() int {
	return xxx_messageInfo_WriteShardResponse.Size(m)
}
func (m *WriteShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteShardResponse proto.InternalMessageInfo

func (m *WriteShardResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WriteShardResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ExecuteStatementRequest struct {
	Statement            string   `protobuf:"bytes,1,opt,name=Statement,proto3" json:"Statement,omitempty"`
	Database             string   `protobuf:"bytes,2,opt,name=Database,proto3" json:"Database,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteStatementRequest) Reset()         { *m = ExecuteStatementRequest{} }
func (m *ExecuteStatementRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementRequest) ProtoMessage()    {}
func (*ExecuteStatementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{2}
}

func (m *ExecuteStatementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStatementRequest.Unmarshal(m, b)
}
func (m *ExecuteStatementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStatementRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteStatementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStatementRequest.Merge(m, src)
}
func (m *ExecuteStatementRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteStatementRequest.Size(m)
}
func (m *ExecuteStatementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStatementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStatementRequest proto.InternalMessageInfo

func (m *ExecuteStatementRequest) GetStatement() string {
	if m != nil {
		return m.Statement
	}
	return ""
}

func (m *ExecuteStatementRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type ExecuteStatementResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteStatementResponse) Reset()         { *m = ExecuteStatementResponse{} }
func (m *ExecuteStatementResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementResponse) ProtoMessage()    {}
func (*ExecuteStatementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{3}
}

func (m *ExecuteStatementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStatementResponse.Unmarshal(m, b)
}
func (m *ExecuteStatementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStatementResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteStatementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStatementResponse.Merge(m, src)
}
func (m *ExecuteStatementResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteStatementResponse.Size(m)
}
func (m *ExecuteStatementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStatementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStatementResponse proto.InternalMessageInfo

func (m *ExecuteStatementResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ExecuteStatementResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateIteratorRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,packed,name=ShardIDs,proto3" json:"ShardIDs,omitempty"`
	Opt                  []byte   `protobuf:"bytes,2,opt,name=Opt,proto3" json:"Opt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIteratorRequest) Reset()         { *m = CreateIteratorRequest{} }
func (m *CreateIteratorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIteratorRequest) ProtoMessage()    {}
func (*CreateIteratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{4}
}

func (m *CreateIteratorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIteratorRequest.Unmarshal(m, b)
}
func (m *CreateIteratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIteratorRequest.Marshal(b, m, deterministic)
}
func (m *CreateIteratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIteratorRequest.Merge(m, src)
}
func (m *CreateIteratorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIteratorRequest.Size(m)
}
func (m *CreateIteratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIteratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIteratorRequest proto.InternalMessageInfo

func (m *CreateIteratorRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *CreateIteratorRequest) GetOpt() []byte {
	if m != nil {
		return m.Opt
	}
	return nil
}

type CreateIteratorResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	DataType             int32    `protobuf:"varint,2,opt,name=DataType,proto3" json:"DataType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIteratorResponse) Reset()         { *m = CreateIteratorResponse{} }
func (m *CreateIteratorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIteratorResponse) ProtoMessage()    {}
func (*CreateIteratorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{5}
}

func (m *CreateIteratorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIteratorResponse.Unmarshal(m, b)
}
func (m *CreateIteratorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIteratorResponse.Marshal(b, m, deterministic)
}
func (m *CreateIteratorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIteratorResponse.Merge(m, src)
}
func (m *CreateIteratorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateIteratorResponse.Size(m)
}
func (m *CreateIteratorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIteratorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIteratorResponse proto.InternalMessageInfo

func (m *CreateIteratorResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreateIteratorResponse) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

type FieldDimensionsRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,packed,name=ShardIDs,proto3" json:"ShardIDs,omitempty"`
	Sources              []byte   `protobuf:"bytes,2,opt,name=Sources,proto3" json:"Sources,omitempty"`
	Start                int64    `protobuf:"varint,3,opt,name=Start,proto3" json:"Start,omitempty"`
	End                  int64    `protobuf:"varint,4,opt,name=End,proto3" json:"End,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldDimensionsRequest) Reset()         { *m = FieldDimensionsRequest{} }
func (m *FieldDimensionsRequest) String() string { return proto.CompactTextString(m) }
func (*FieldDimensionsRequest) ProtoMessage()    {}
func (*FieldDimensionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{6}
}

func (m *FieldDimensionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDimensionsRequest.Unmarshal(m, b)
}
func (m *FieldDimensionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDimensionsRequest.Marshal(b, m, deterministic)
}
func (m *FieldDimensionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDimensionsRequest.Merge(m, src)
}
func (m *FieldDimensionsRequest) XXX_Size() int {
	return xxx_messageInfo_FieldDimensionsRequest.Size(m)
}
func (m *FieldDimensionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDimensionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDimensionsRequest proto.InternalMessageInfo

func (m *FieldDimensionsRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *FieldDimensionsRequest) GetSources() []byte {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *FieldDimensionsRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *FieldDimensionsRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type FieldDimensionsResponse struct {
	Fields               map[string]int32 `protobuf:"bytes,1,rep,name=Fields,proto3" json:"Fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Dimensions           []string         `protobuf:"bytes,2,rep,name=Dimensions,proto3" json:"Dimensions,omitempty"`
	Err                  string           `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FieldDimensionsResponse) Reset()         { *m = FieldDimensionsResponse{} }
func (m *FieldDimensionsResponse) String() string { return proto.CompactTextString(m) }
func (*FieldDimensionsResponse) ProtoMessage()    {}
func (*FieldDimensionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{7}
}

func (m *FieldDimensionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDimensionsResponse.Unmarshal(m, b)
}
func (m *FieldDimensionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDimensionsResponse.Marshal(b, m, deterministic)
}
func (m *FieldDimensionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDimensionsResponse.Merge(m, src)
}
func (m *FieldDimensionsResponse) XXX_Size() int {
	return xxx_messageInfo_FieldDimensionsResponse.Size(m)
}
func (m *FieldDimensionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDimensionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDimensionsResponse proto.InternalMessageInfo

func (m *FieldDimensionsResponse) GetFields() map[string]int32 {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *FieldDimensionsResponse) GetDimensions() []string {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *FieldDimensionsResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type SeriesKeysRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,packed,name=ShardIDs,proto3" json:"ShardIDs,omitempty"`
	Opt                  []byte   `protobuf:"bytes,2,opt,name=Opt,proto3" json:"Opt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeriesKeysRequest) Reset()         { *m = SeriesKeysRequest{} }
func (m *SeriesKeysRequest) String() string { return proto.CompactTextString(m) }
func (*SeriesKeysRequest) ProtoMessage()    {}
func (*SeriesKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{8}
}

func (m *SeriesKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeriesKeysRequest.Unmarshal(m, b)
}
func (m *SeriesKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeriesKeysRequest.Marshal(b, m, deterministic)
}
func (m *SeriesKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeriesKeysRequest.Merge(m, src)
}
func (m *SeriesKeysRequest) XXX_Size() int {
	return xxx_messageInfo_SeriesKeysRequest.Size(m)
}
func (m *SeriesKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeriesKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeriesKeysRequest proto.InternalMessageInfo

func (m *SeriesKeysRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *SeriesKeysRequest) GetOpt() []byte {
	if m != nil {
		return m.Opt
	}
	return nil
}

type SeriesKeysResponse struct {
	SeriesList           []byte   `protobuf:"bytes,1,opt,name=SeriesList,proto3" json:"SeriesList,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeriesKeysResponse) Reset()         { *m = SeriesKeysResponse{} }
func (m *SeriesKeysResponse) String() string { return proto.CompactTextString(m) }
func (*SeriesKeysResponse) ProtoMessage()    {}
func (*SeriesKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_993f119417e3f9c8, []int{9}
}

func (m *SeriesKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeriesKeysResponse.Unmarshal(m, b)
}
func (m *SeriesKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeriesKeysResponse.Marshal(b, m, deterministic)
}
func (m *SeriesKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeriesKeysResponse.Merge(m, src)
}
func (m *SeriesKeysResponse) XXX_Size() int {
	return xxx_messageInfo_SeriesKeysResponse.Size(m)
}
func (m *SeriesKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SeriesKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SeriesKeysResponse proto.InternalMessageInfo

func (m *SeriesKeysResponse) GetSeriesList() []byte {
	if m != nil {
		return m.SeriesList
	}
	return nil
}

func (m *SeriesKeysResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*WriteShardRequest)(nil), "internal.WriteShardRequest")
	proto.RegisterType((*WriteShardResponse)(nil), "internal.WriteShardResponse")
	proto.RegisterType((*ExecuteStatementRequest)(nil), "internal.ExecuteStatementRequest")
	proto.RegisterType((*ExecuteStatementResponse)(nil), "internal.ExecuteStatementResponse")
	proto.RegisterType((*CreateIteratorRequest)(nil), "internal.CreateIteratorRequest")
	proto.RegisterType((*CreateIteratorResponse)(nil), "internal.CreateIteratorResponse")
	proto.RegisterType((*FieldDimensionsRequest)(nil), "internal.FieldDimensionsRequest")
	proto.RegisterType((*FieldDimensionsResponse)(nil), "internal.FieldDimensionsResponse")
	proto.RegisterMapType((map[string]int32)(nil), "internal.FieldDimensionsResponse.FieldsEntry")
	proto.RegisterType((*SeriesKeysRequest)(nil), "internal.SeriesKeysRequest")
	proto.RegisterType((*SeriesKeysResponse)(nil), "internal.SeriesKeysResponse")
}

func init() { proto.RegisterFile("cluster/internal/data.proto", fileDescriptor_993f119417e3f9c8) }

var fileDescriptor_993f119417e3f9c8 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0x92, 0xb6, 0xb4, 0x77, 0x95, 0xd8, 0x2c, 0xe8, 0xa2, 0x82, 0xa6, 0x2a, 0x4f, 0x79,
	0xa1, 0x93, 0xe0, 0x05, 0x78, 0x83, 0x35, 0x13, 0x13, 0x20, 0x26, 0x07, 0x89, 0x67, 0xaf, 0xb9,
	0x02, 0x6b, 0x99, 0x5d, 0xec, 0x9b, 0x89, 0x7c, 0x03, 0xdf, 0xc6, 0x3f, 0xa1, 0x38, 0x71, 0x96,
	0x6d, 0x42, 0x42, 0x7b, 0xbb, 0xe7, 0xe4, 0xfa, 0xf8, 0x9c, 0xeb, 0x1b, 0x78, 0xb6, 0x2d, 0x2b,
	0x4b, 0x68, 0x8e, 0xa5, 0x22, 0x34, 0x4a, 0x94, 0xc7, 0x85, 0x20, 0xb1, 0xde, 0x19, 0x4d, 0x9a,
	0x4d, 0x3d, 0x99, 0xfc, 0x0e, 0xe0, 0xe0, 0x9b, 0x91, 0x84, 0xf9, 0x0f, 0x61, 0x0a, 0x8e, 0x3f,
	0x2b, 0xb4, 0xc4, 0x62, 0x78, 0xe4, 0xf0, 0xd9, 0x26, 0x0e, 0x56, 0x41, 0x3a, 0xe2, 0x1e, 0xb2,
	0x05, 0x4c, 0xce, 0xb5, 0x54, 0x64, 0xe3, 0x70, 0x15, 0xa5, 0x73, 0xde, 0x21, 0xb6, 0x84, 0xe9,
	0x46, 0x90, 0xb8, 0x10, 0x16, 0xe3, 0x68, 0x15, 0xa4, 0x33, 0xde, 0x63, 0x96, 0xc2, 0x63, 0x8e,
	0x84, 0x8a, 0xa4, 0x56, 0xe7, 0xba, 0x94, 0xdb, 0x3a, 0x1e, 0xb9, 0x96, 0xbb, 0x74, 0xf2, 0x1e,
	0xd8, 0xd0, 0x8c, 0xdd, 0x69, 0x65, 0x91, 0x31, 0x18, 0x9d, 0xe8, 0x02, 0x9d, 0x95, 0x31, 0x77,
	0x75, 0xe3, 0xf0, 0x33, 0x5a, 0x2b, 0xbe, 0x63, 0x1c, 0x3a, 0x2d, 0x0f, 0x93, 0x1c, 0x0e, 0xb3,
	0x5f, 0xb8, 0xad, 0x08, 0x73, 0x12, 0x84, 0x57, 0xa8, 0xc8, 0xc7, 0x7a, 0x0e, 0xb3, 0x9e, 0x73,
	0x6a, 0x33, 0x7e, 0x43, 0xdc, 0x8a, 0x10, 0xde, 0x8e, 0x90, 0x7c, 0x80, 0xf8, 0xbe, 0xe8, 0x83,
	0xec, 0x65, 0xf0, 0xf4, 0xc4, 0xa0, 0x20, 0x3c, 0x23, 0x34, 0x82, 0xb4, 0xf1, 0xe6, 0x96, 0x30,
	0xed, 0x86, 0x6c, 0xe3, 0x60, 0x15, 0xa5, 0x23, 0xde, 0x63, 0xb6, 0x0f, 0xd1, 0x97, 0x1d, 0x39,
	0xa9, 0x39, 0x6f, 0xca, 0xe4, 0x14, 0x16, 0x77, 0x65, 0x3a, 0x3b, 0xfb, 0x10, 0x65, 0xc6, 0x74,
	0xf1, 0x9a, 0xd2, 0x07, 0xfb, 0x5a, 0xef, 0x5a, 0x37, 0x63, 0xde, 0xe3, 0xe4, 0x1a, 0x16, 0xa7,
	0x12, 0xcb, 0x62, 0x23, 0xaf, 0x50, 0x59, 0xa9, 0x95, 0xfd, 0x1f, 0x3f, 0xcd, 0x7e, 0xe8, 0xca,
	0x6c, 0xd1, 0x76, 0x9e, 0x3c, 0x64, 0x4f, 0x60, 0x9c, 0x93, 0x30, 0xe4, 0x96, 0x20, 0xe2, 0x2d,
	0x70, 0x9e, 0x54, 0xe1, 0x5e, 0x3d, 0xe2, 0x4d, 0x99, 0xfc, 0x09, 0xe0, 0xf0, 0xde, 0xc5, 0x5d,
	0x82, 0x0c, 0x26, 0xee, 0x53, 0x7b, 0xef, 0xde, 0xcb, 0x17, 0x6b, 0xbf, 0xae, 0xeb, 0x7f, 0x1c,
	0x69, 0x79, 0x9b, 0x29, 0x32, 0x35, 0xef, 0x0e, 0xb3, 0x23, 0x80, 0x9b, 0x4e, 0xb7, 0xae, 0x33,
	0x3e, 0x60, 0xfc, 0xa0, 0xa2, 0x7e, 0x50, 0xcb, 0x37, 0xb0, 0x37, 0x10, 0x6a, 0x1a, 0x2e, 0xb1,
	0xf6, 0x93, 0xbc, 0xc4, 0xba, 0x49, 0x77, 0x2d, 0xca, 0xca, 0x8f, 0xb1, 0x05, 0x6f, 0xc3, 0xd7,
	0x41, 0xf2, 0x0e, 0x0e, 0x72, 0x34, 0x12, 0xed, 0x47, 0xac, 0xed, 0x43, 0x9f, 0x94, 0x0d, 0x25,
	0xba, 0x61, 0x1c, 0x01, 0xb4, 0xec, 0x27, 0x69, 0xdb, 0xa5, 0x9d, 0xf3, 0x01, 0xe3, 0x53, 0x84,
	0x7d, 0x8a, 0x8b, 0x89, 0xfb, 0xc7, 0x5f, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x57, 0xbb, 0x0a,
	0xc2, 0x02, 0x04, 0x00, 0x00,
}
